name: Test trigger

on:
  workflow_dispatch:
    inputs:
      result: 
      pr_id: 
  pull_request:

jobs:
  
  # tady se spusti test pipeline
  main-job:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: echo "Ahoj!"
      - name: show_time
        run: date +"%T"
      - name: reference
        run: echo "$(cut -d'/' -f3 <<< $GITHUB_REF )"
  
  set-pr-status-pending:
    outputs: 
      pr_id: ${{ steps.pr_id_output.outputs.pr_id }}
    needs: [main-job]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      #GitHub PAT here
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - name: Save repo pull request number
        run: echo "GH_PULL_REQUEST_ID=$(cut -d'/' -f3 <<< $GITHUB_REF )" >> $GITHUB_ENV
      - name: pr_id_output
        run: echo "::set-output name=pr_id::${{ env.GH_PULL_REQUEST_ID }}"
      - name: Set PR Context Status to PENDING
        uses: gpuliyar/pr-status-action@v1.0.0
        with:
          repository: viliam-gago/test-branch-prot
          pr-number: ${{ env.GH_PULL_REQUEST_ID }}
          context: Pipeline status
          state: pending
          description: Waiting to be resolved.

  start-test-pipeline-monitor:
    needs: set-pr-status-pending
    runs-on: ubuntu-latest     
    steps:
      - name: Show output of prev   
        run: echo ${{needs.set-pr-status-pending.outputs.pr_id}}



    



