name: Test trigger

on:
  workflow_dispatch:
  pull_request:



jobs:
  
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: echo "Ahoj!"
      - name: show_time
        run: date +"%T"
      - name: reference
        run: echo "$(cut -d'/' -f3 <<< $GITHUB_REF )"
  
  set-pr-status:
    needs: [main-job]
    runs-on: ubuntu-latest
    steps:
    - name: Event
      run: echo ${{ github.event_name }}
    - name: Save repo pull request number
      run: echo "GH_PULL_REQUEST=$(cut -d'/' -f3 <<< $GITHUB_REF )" >> $GITHUB_ENV
    - name: Set PR Context Status to Success
      uses: gpuliyar/pr-status-action@v1.0.0
      with:
        repository: viliam-gago/test-branch-prot
        pr-number: ${{ env.GH_PULL_REQUEST }}
        context: aaaa
        state: pending
        description: Waiting to be resolved.
      env:
          #GitHub PAT here
          GITHUB_TOKEN: ${{ secrets.token }}



