name: Test trigger

on:
  pull_request:
#   schedule:
#     - cron: '15 13 * * *'


jobs:
  
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: echo "Ahoj!"
      - name: show_time
        run: date +"%T"
      - name: reference
        run: echo "$(cut -d'/' -f3 <<< $GITHUB_REF )"
  
  set-pr-status:
    needs: [main-job]
    runs-on: ubuntu-latest
    steps:
    - name: echo something
      run: echo hello
    - name: Set PR Context Status to Success
      uses: gpuliyar/pr-status-action@v1.0.0
      with:
        repository: viliam-gago/test-branch-prot
        pr-number: ${{ cut -d'/' -f3 <<< $GITHUB_REF }}
        context: aaaa
        state: pending
        description: Waiting to be resolved.
      env:
          # Default Github Token
          GITHUB_TOKEN: ${{ secrets.token }}



