name: trigger pr wf

on:
  workflow_dispatch:

jobs:
  set-pr-status:
    runs-on: ubuntu-latest
    steps:
    - name: echo something
      run: echo hello
    - name: Set PR Context Status to Success
      uses: gpuliyar/pr-status-action@v1.0.0
      with:
        # Repository name (Mandatory)
        repository: viliam-gago/test-branch-prot

        # PR Number  (Mandatory)
        pr-number: 4

        # Name the context to use in the PR  (Mandatory)
        context: feature_branch2

        # State to apply (Mandatory)
        # Any of the (error | failure | pending | success) states
        state: success

        # A short description of the status (Mandatory)
        description: This is so awesome to use a context in a PR

      env:
        # Default Github Token
        GITHUB_TOKEN: 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